config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :users
  resources :authors
  resources :books
  resources :posts
  resources :categories
  
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "welcome#index"
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :brief)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Brief:</strong>
    <%= author.brief %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :brief, style: "display: block" %>
    <%= form.text_area :brief %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<%= link_to "New author", new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>